# Faithfulness

FaithfulnessCorrelation: False # -1 to 1
fc_nr_runs: 100
fc_subset_size: 224
fc_perturb_baseline: "black"

FaithfulnessEstimate: False
fe_features_in_step: 224
fe_perturb_baseline: "black"

MonotonicityCorrelation: False
mc_nr_samples: 10
mc_features_in_step: 3136
mc_perturb_baseline: "uniform"

PixelFlipping: False
pf_features_in_step: 224
pf_perturb_baseline: "black"

RegionPerturbation: False
rp_patch_size: 14
rp_regions_evaluation: 10
rp_perturb_baseline: "uniform"

InsertionDeletion: False
id_pixel_batch_size: 50
id_sigma: 5.0

IROF: False
irof_segmentation_method: "slic"
irof_perturb_baseline: "mean"

ROAD: False
road_noise: 0.1
road_percentages_max: 100

Sufficiency: True
su_threshold: 0.6


# Robustness

LocalLipschitzEstimate: False
lle_nr_samples: 5
lle_perturb_std: 0.2
lle_perturb_mean: 0.0

MaxSensitivity: False
ms_nr_samples: 10
ms_lower_bound: 0.2

Continuity: False
co_patch_size: 56
co_nr_steps: 20
co_perturb_baseline: "uniform"

RelativeInputStability: False
ris_nr_samples: 5

RelativeOutputStability: False
ros_nr_samples: 5

RelativeRepresentationStability: False
rrs_nr_samples: 5

Infidelity: True
in_n_perturb_samples: 50

# Usability

Sparseness: False

Complexity: False

EffectiveComplexity: False
ec_eps: 0.00001

# util
normalise: False
device: "cuda:0"