# Batch:
feature_permutation: False

feature_ablatation: False
fa_baselines: 0

gcam: True

scam: True
scam_batch_size: 32

gcampp: True

# Single:
occlusion: True
occ_strides: 25
occ_sliding_window_shapes: 50
occ_baselines: 0

lime: True
lime_alpha: 0.5
lime_n_samples: 100
lime_perturbations_per_eval: 5

kernel_shap: True
ks_baselines: 0
ks_n_samples: 100
ks_perturbations_per_eval: 5

saliency: True

input_x_gradient: True

guided_backprob: True

ig: True
ig_baselines: 0
ig_n_steps: 80

eg: True
eg_n_samples: 80 # 80
eg_stdevs: 0.001 # 0.001

deeplift: True
dl_eps: 0.000000001
dl_baselines: 0


deeplift_shap: True

lrp: True
lrp_eps: 0.001

