occlusion:
  strides: 4
  sliding_window_shapes: 7
  baselines: 0
  perturbations_per_eval: 1
  show_progress: False  

lime:
  alpha: 1.0
  n_samples: 10
  perturbations_per_eval: 5 

kernelshap:
  baselines: 0
  n_samples: 10
  perturbations_per_eval: 5

saliency: {}

inputxgradient: {}

guidedbackprop: {}

gradcam: {}

scorecam:
  batch_size: 64

gradcamplusplus: {}

integratedgradients:
  baselines: 0
  n_steps: 30

expectedgradients:
  n_samples: 40
  stdevs: 0.001

deeplift:
  eps: 0.000000001
  baselines: 0

deepliftshap: {}

lrp:
  eps: 0.0001
  gamma: 0.25

attention: {}

attentionrollout: {}

attentionlrp: {}

