# @package _global_

defaults:
  - _self_
  - data: imagenet.yaml # choose datamodule with `test_dataloader()` for evaluation
  - logger: null
  - paths: default.yaml
  - eval_method: image.yaml
  - xai_method: image.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]
time: ${now:%Y-%m-%d}_${now:%H-%M-%S}

# passing checkpoint path is necessary for evaluation
ckpt_path: "data/model_weights/"
attr_path: "/attr_imagenet_dataset_14_methods_2023-04-20_14-29-59.npz"
