# @package _global_

defaults:
  - _self_
  - data: modelnet40.yaml # choose datamodule with `test_dataloader()` for evaluation
  - logger: null
  - paths: default.yaml
  - eval_method: point_cloud.yaml
  - xai_method: point_cloud.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]
time: ${now:%Y-%m-%d}_${now:%H-%M-%S}

# passing checkpoint path is necessary for evaluation
ckpt_path: "data/model_weights/"
attr_path: "/attr_shapenet_dataset_11_methods_2023-05-26_12-11-22.npz"
