# @package _global_

defaults:
  - _self_
  - data: imagenet.yaml # choose datamodule with `test_dataloader()` for evaluation
  - logger: null
  - paths: default.yaml
  - xai_method: image.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "explain"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: "data/model_weights/"
