# @package _global_

defaults:
  - _self_
  - paths: default.yaml
  - hydra: default.yaml
  - logger: null
  - extras: null


task_name: "rank"

tags: ["dev"]
time: ${now:%Y-%m-%d}_${now:%H-%M-%S}

full_ranking: True
idx_model: 0 # Only if full_ranking = True

file_image_inet: "/Image/eval_imagenet_dataset.npz"
file_image_oct: "/Image/eval_oct_dataset.npz"
file_image_r45: "/Image/eval_resisc45_dataset.npz"

file_volume_adr: "/Volume/eval_AdrenalMNIST3D_dataset.npz"
file_volume_org: "/Volume/eval_OrganMNIST3D_dataset.npz"
file_volume_ves: "/Volume/eval_VesselMNIST3D_dataset.npz"

file_pc_coma: "/Point_Cloud/eval_coma_dataset.npz"
file_pc_m40: "/Point_Cloud/eval_modelnet40_dataset.npz"
file_pc_shpn: "/Point_Cloud/eval_shapenet_dataset.npz"
