# Faithfulness

faithfulnesscorrelation:
  nr_runs: 100
  subset_size: 224
  perturb_baseline: "black"

faithfulnessestimate:
  features_in_step: 224
  perturb_baseline: "black"

monotonicitycorrelation:
  nr_samples: 10
  features_in_step: 3136
  perturb_baseline: "uniform"

pixelflipping:
  features_in_step: 224
  perturb_baseline: "black"

regionperturbation:
  patch_size: 14
  regions_evaluation: 10
  perturb_baseline: "uniform"

insertion:
  pixel_batch_size: 50 
  sigma: 5.0
  kernel_size: 15

deletion:
  pixel_batch_size: 50

irof:
  segmentation_method: "slic"
  perturb_baseline: "mean"

road:
  noise: 0.1
  percentages_max: 100

sufficiency:
  threshold: 0.9

infidelity:
  n_perturb_samples: 50

# Robustness

locallipschitzestimate:
  nr_samples: 5
  perturb_std: 0.1
  perturb_mean: 0.0

maxsensitivity:
  nr_samples: 10
  lower_bound: 0.2

continuity:
  patch_size: 56
  nr_steps: 20
  perturb_baseline: "uniform"

relativeinputstability:
  nr_samples: 10

relativeoutputstability:
  nr_samples: 10

relativerepresentationstability:
  nr_samples: 10

# Complexity

sparseness: {}

complexity: {}

effectivecomplexity:
  eps: 0.01
