# Faithfulness

faithfulnesscorrelation:
  nr_runs: 100
  subset_size: 56
  perturb_baseline: "black"

faithfulnessestimate:
  features_in_step: 56
  perturb_baseline: "black"

monotonicitycorrelation:
  nr_samples: 10
  features_in_step: 392
  perturb_baseline: "uniform"

pixelflipping:
  features_in_step: 56
  perturb_baseline: "black"

regionperturbation:
  patch_size: 4
  regions_evaluation: 20
  perturb_baseline: "uniform"

insertion:
  pixel_batch_size: 50 
  sigma: 2.5
  kernel_size: 1

deletion:
  pixel_batch_size: 50

irof:
  segmentation_method: "slic"
  perturb_baseline: "black"

road:
  noise: 50
  percentages_max: 100

sufficiency:
  threshold: 0.0002

infidelity:
  n_perturb_samples: 50

# Robustness

locallipschitzestimate:
  nr_samples: 10
  perturb_std: 0.2
  perturb_mean: 0.0

maxsensitivity:
  nr_samples: 10
  lower_bound: 0.2

continuity:
  patch_size: 7
  nr_steps: 20
  perturb_baseline: "uniform"

relativeinputstability:
  nr_samples: 10

relativeoutputstability:
  nr_samples: 10

relativerepresentationstability:
  nr_samples: 10

# Complexity

sparseness: {}

complexity: {}

effectivecomplexity:
  eps: 0.001